#define CAN_ID_LEFT_SHOULDER_PITCH 0x01
#define CAN_ID_LEFT_SHOULDER_ROLL 0x02
#define CAN_ID_LEFT_SHOULDER_YAW 0x03
#define CAN_ID_LEFT_ELBOW 0x04
#define CAN_ID_LEFT_WRIST_ROLL 0x05
#define CAN_ID_LEFT_WRIST_PITCH 0x06
#define CAN_ID_LEFT_WRIST_YAW 0x07
#define CAN_ID_LEFT_EE 0x08
#define CAN_ID_RIGHT_SHOULDER_PITCH 0x11
#define CAN_ID_RIGHT_SHOULDER_ROLL 0x12
#define CAN_ID_RIGHT_SHOULDER_YAW 0x13
#define CAN_ID_RIGHT_ELBOW 0x14
#define CAN_ID_RIGHT_WRIST_ROLL 0x15
#define CAN_ID_RIGHT_WRIST_PITCH 0x16
#define CAN_ID_RIGHT_WRIST_YAW 0x17
#define CAN_ID_RIGHT_EE 0x18


